// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkEEaC1HMaqECXiHHAAFXDxK9d8eYdRFQ',
    appId: '1:1043117011114:web:f8000d47b1e309907020d3',
    messagingSenderId: '1043117011114',
    projectId: 'sikepi',
    authDomain: 'sikepi.firebaseapp.com',
    storageBucket: 'sikepi.appspot.com',
    measurementId: 'G-3KDC6DLQCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkG3zUt6Pu0V4DJmCGBPvEKROHzKBPj_o',
    appId: '1:1043117011114:android:c12188184745b8117020d3',
    messagingSenderId: '1043117011114',
    projectId: 'sikepi',
    storageBucket: 'sikepi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAFrVfaiPmFT32o7WmLXB4B3HerFAKTJM',
    appId: '1:1043117011114:ios:33233ef1335f22707020d3',
    messagingSenderId: '1043117011114',
    projectId: 'sikepi',
    storageBucket: 'sikepi.appspot.com',
    androidClientId: '1043117011114-k1jb66hf4sh2df9flq3c3ke9mpl9267k.apps.googleusercontent.com',
    iosClientId: '1043117011114-etfsf3phei7v10351o72tqrp254jjtd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hmjApps',
  );
}
